[package]
name = "elements"
version = "0.5.0"
authors = ["Andrew Poelstra <apoelstra@blockstream.com>"]
description = "Library with support for de/serialization, parsing and executing on data structures and network messages related to Elements"
license = "CC0-1.0"
homepage = "https://github.com/ElementsProject/rust-elements/"
repository = "https://github.com/ElementsProject/rust-elements/"
documentation = "https://docs.rs/elements/"

[features]
"serde-feature" = [
    "bitcoin/serde",
    "serde"
]
"fuzztarget" = []

[dependencies]
secp256k1 = "0.12.0"

[dependencies.bitcoin]
version = "0.16.0"

[dependencies.serde]
version = "1.0"
optional = true

