[package]
name = "elements"
version = "0.1.1"
authors = ["Andrew Poelstra <apoelstra@blockstream.com>"]
description = "Library with support for de/serialization, parsing and executing on data structures and network messages related to Elements"
license = "CC0-1.0"

[features]
"serde-feature" = [
    "bitcoin/serde",
    "serde"
]
"fuzztarget" = []

[dependencies]
secp256k1 = "0.11.0"

[dependencies.bitcoin]
version = "0.14.0"
path = "../../rust-bitcoin/rust-bitcoin/"

[dependencies.serde]
version = "1.0"
optional = true

